# Imagem Docker
FROM ubuntu:21.04

RUN apt-get update && apt-get install -y nano locate apt-file dmidecode libgl1 libfreetype6 libfontconfig1 \
    libxslt1.1 libxkbcommon-x11-0 libnss3 libdbus-1-3 libxss1 libglib2.0-0 libasound2 libxcomposite1 && apt-get clean

COPY docker/build/licserver/entrypoint-licserver.sh /opt

EXPOSE 5555

CMD /opt/entrypoint-licserver.sh